export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const ADD_FAVORITES_PRODUCTS = 'ADD_FAVORITES_PRODUCTS';
export const DELETE_FAVORITES_PRODUCTS = 'DELETE_FAVORITES_PRODUCTS';
export const INCREASE_TO_CART = 'INCREASE_TO_CART';
export const DECREASE_TO_CART = 'DECREASE_TO_CART';
